name: tenancy
channels:
  - defaults
dependencies:
  - python=3.11.4
  - requests=2.31.0
  - psycopg2=2.9.3
  - python-dotenv==0.21.0
  - pip=23.2.1
  - pip:
    - pyjwt[crypto]
    - tableauhyperapi
    - tableauserverclient
